name: UltimatePlugin
version: '1.19.4'
main: me.galaxy1007.tutoplug.UltimateMain
api-version: 1.19
commands:
  fly:
    description: Vlieg als een vogel!
    usage: /<command>
    permission: UltimatePlugin.fly
  vanish:
    description: Verberg jezelf!
    usage: /<command>
    permission: UltimatePlugin.vanish
    aliases:
      - v
  armorstand:
    description: Maak een armorstand aan.
    usage: /<command>
    permission: UltimatePlugin.armorstand
    aliases:
      - as
  heal:
    description: genees jezelf!
    usage: /<command>
    aliases:
      - h
