name: UltimatePlugin
version: '1.19.4'
main: me.galaxy1007.tutoplug.UltimateMain
api-version: 1.19
commands:
  fly:
    description: Vlieg als een vogel!
    usage: /<command>
    permission: UltimatePlugin.fly
  vanish:
    description: Verberg jezelf!
    usage: /<command>
    permission: UltimatePlugin.vanish
  gui:
    description: Open het plugin GUI.
    usage: /<command>
    permission: UltimatePlugin.gui

